# Generated by Django 4.0.4 on 2022-04-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_location_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday', models.DateField(auto_now_add=True)),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.location')),
            ],
            options={
                'verbose_name_plural': 'Timecards',
            },
        ),
    ]
