# Generated by Django 4.0.4 on 2022-04-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Work day',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workday.workday')),
            ],
            options={
                'verbose_name_plural': 'Timesheet records',
            },
        ),
    ]
