# Generated by Django 4.0.4 on 2022-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='clock_out',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
