# Generated by Django 4.0.4 on 2022-04-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0005_alter_workday_clock_in_alter_workday_clock_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
