# Generated by Django 4.0.4 on 2022-04-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0006_alter_workday_clock_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workday.workday'),
        ),
    ]
