# Generated by Django 4.0.4 on 2022-04-13 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ssn', models.IntegerField(unique=True, verbose_name='Social security number')),
                ('home_address', models.CharField(max_length=65, verbose_name='Home address')),
                ('phone_num', models.CharField(max_length=15, verbose_name='Phone number')),
                ('specialty', models.CharField(max_length=65, verbose_name='Specialty fo the doctor')),
                ('office_address', models.CharField(max_length=150, verbose_name='Office address')),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
