# Generated by Django 4.0.4 on 2022-04-16 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('isDoctor', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ssn', models.IntegerField(unique=True, verbose_name='Social security number')),
                ('home_address', models.CharField(max_length=65, verbose_name='Home address')),
                ('phone_num', models.CharField(max_length=15, verbose_name='Phone number')),
                ('specialty', models.CharField(max_length=65, verbose_name='Specialty fo the doctor')),
                ('office_address', models.CharField(max_length=150, verbose_name='Office address')),
                ('isWest', models.BooleanField(blank=True, verbose_name='is from west?')),
                ('isEast', models.BooleanField(blank=True, verbose_name='is from east?')),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Name of the location')),
                ('isWest', models.BooleanField(blank=True, verbose_name='is from west?')),
                ('isEast', models.BooleanField(blank=True, verbose_name='is from east?')),
                ('isActive', models.BooleanField(blank=True, verbose_name='still active?')),
                ('address', models.CharField(max_length=125, verbose_name='Address of the location')),
            ],
            options={
                'verbose_name_plural': 'Locations available',
            },
        ),
    ]
