# Generated by Django 4.0.4 on 2022-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_location_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='still active?'),
        ),
    ]
